### ISSUE TITLE
When the data stored only in one node  still can LOAD the data in local path 

### ISSUE THREAD

**Issue by Zhangshunyu** [HuaweiBigData/astro#9]
Now we load the data using LOAD function, when we specify the data file in LOCAL path who is 
stored on only one node, the task occasionally goes wrong, because the LOAD function uses 
“sc.textFile(path)” to generate the RDD in BULKLOAD command. While sometimes if the task runs on the executor whose node has the data file, it will load successfully. Can astro optimize the LOAD 
function to make it be able to load the data file who was stored only in one node？

**Comment by ravipesala** [comment]
You are right, LOAD internally uses ```sc.textFile(path)``` to create RDD in bulkload. There would not be any issues If the file is located in HDFS as it is visible to all nodes. But if the file located in local file system of one node then there is possibilities of failing.I guess It is strongly suggested that user should keep the file in HDFS before doing bulkload. Because it is the same way Spark also handles the local files.

**Comment by Zhangshunyu** [comment]
The PR for this issue ：
https://github.com/HuaweiBigData/astro/pull/12#discussion_r42471472

**Comment by ravipesala** [comment]
Please close the issue
